#cloud-config
<<<<<<< HEAD
timezone: UTC

package_update: true
package_upgrade: true
package_reboot_if_required: true
=======
timezone: ${timezone}
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe

packages:
  - git

runcmd:
<<<<<<< HEAD
  - git clone https://github.com/fierytermite/tpotce /root/tpot
  - /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf
  - rm /root/tpot.conf
  - /sbin/shutdown -r +5

# The contents of tpot.conf will be base64 encoded and appended to this file
# via the terraform configuration in main.tf
#
# Make sure there are no trailing new lines after "permissions" below
write_files:
  - encoding: b64
=======
  - git clone https://github.com/fierytermite/tpotce /root/tpot
  - /root/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf
  - rm /root/tpot.conf
  - /sbin/shutdown -r now

password: ${password}
chpasswd:
  expire: false

write_files:
  - content: |
      # tpot configuration file
      myCONF_TPOT_FLAVOR='${tpot_flavor}'
      myCONF_WEB_USER='${web_user}'
      myCONF_WEB_PW='${web_password}'
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    owner: root:root
    path: /root/tpot.conf
    permissions: '0600'
