version: '2.3'

networks:
  mailoney_local:

services:

# Mailoney service
  mailoney:
    build: .
    container_name: mailoney
    restart: always
    environment:
     - HPFEEDS_SERVER=
     - HPFEEDS_IDENT=user
     - HPFEEDS_SECRET=pass
     - HPFEEDS_PORT=20000
     - HPFEEDS_CHANNELPREFIX=prefix
    networks:
     - mailoney_local
    ports:
     - "25:25"
<<<<<<< HEAD
    image: "dtagdevsec/mailoney:1903"
=======
    image: "dtagdevsec/mailoney:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    read_only: true
    volumes:
     - /data/mailoney/log:/opt/mailoney/logs
