version: '2.3'

networks:
  cyberchef_local:

services:

# Cyberchef service
  cyberchef:
    build: .
    container_name: cyberchef
    restart: always
    networks:
     - cyberchef_local
    ports:
     - "127.0.0.1:64299:8000"
<<<<<<< HEAD
    image: "dtagdevsec/cyberchef:1903"
=======
    image: "dtagdevsec/cyberchef:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    read_only: true
