version: '2.3'

services:

## Elasticsearch-head service
  head:
    build: .
    container_name: head
    restart: always
    #    depends_on:
    #      elasticsearch:
    #        condition: service_healthy
    ports:
     - "127.0.0.1:64302:9100"
<<<<<<< HEAD
    image: "dtagdevsec/head:1903"
=======
    image: "dtagdevsec/head:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    read_only: true
