version: '2.3'

services:

# Suricata service
  suricata:
    build: .
    container_name: suricata
    restart: always
    environment:
    # For ET Pro ruleset replace "OPEN" with your OINKCODE
     - OINKCODE=OPEN
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
<<<<<<< HEAD
    image: "dtagdevsec/suricata:1903"
=======
    image: "dtagdevsec/suricata:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    volumes:
     - /data/suricata/log:/var/log/suricata
