version: '2.3'

services:

## Kibana service
  kibana:
    build: .
    container_name: kibana
    restart: always
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
    ports:
     - "127.0.0.1:64296:5601"
<<<<<<< HEAD
    image: "dtagdevsec/kibana:1903"
=======
    image: "dtagdevsec/kibana:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
