version: '2.3'

networks:
  spiderfoot_local:

services:

# Spiderfoot service
  spiderfoot:
    build: .
    container_name: spiderfoot
    restart: always
    networks:
     - spiderfoot_local
    ports:
     - "127.0.0.1:64303:8080"
<<<<<<< HEAD
    image: "dtagdevsec/spiderfoot:1903"
=======
    image: "dtagdevsec/spiderfoot:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    volumes:
     - /data/spiderfoot/spiderfoot.db:/home/spiderfoot/spiderfoot.db
