version: '2.3'

services:

# Fatt service
  fatt:
    build: .
    container_name: fatt
    restart: always
    network_mode: "host"
    cap_add:
     - NET_ADMIN
     - SYS_NICE
     - NET_RAW
<<<<<<< HEAD
    image: "dtagdevsec/fatt:1903"
=======
    image: "dtagdevsec/fatt:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    volumes:
     - /data/fatt/log:/opt/fatt/log
