version: '2.3'

services:

# P0f service
  p0f:
    build: .
    container_name: p0f
    restart: always
    network_mode: "host"
<<<<<<< HEAD
    image: "dtagdevsec/p0f:1903"
=======
    image: "dtagdevsec/p0f:2006"
>>>>>>> be1a90524a9a12693fd2f46c2f7fc1bc18825bfe
    read_only: true
    volumes:
     - /data/p0f/log:/var/log/p0f
